apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    componente: web
spec:
  containers:
    - name: client
      image: ruchavarri/multi-client
      ports:
        - containerPort: 3000